spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    open-in-view: false

logging:
  level:
    root: INFO
    com.adrovis: INFO
    org.hibernate.SQL: WARN
    org.springframework.web: WARN

app:
  cors:
    allowed-origins:
      - https://adrovis.com
      - https://www.adrovis.com

  async:
    core-pool-size: 4
    max-pool-size: 10
    queue-capacity: 200
    await-termination-seconds: 30

  mail:
    from: ${MAIL_FROM}

  api:
    base-url: ${APP_BASE_URL}
    environment-label: Production

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false